name: "[CD] Continuous Delivery"

# on:
#     push:
#         branches: [main]

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            ## [COMMON_CI_Steps]
            - uses: actions/checkout@v3
            ## =================
            - name: "Debug"
              run: "ls -la"
            ## Poderia ser utilizado o 'npm install' mas 
            ## no caso do processo de CI/CD é mais interessante e performatico
            ## utilizar o comando 'npm ci' que instala apenas o necessário
            ## para executar a pipeline
            - name: "Install Dependencies"
              run: "npm ci"
            - name: "Install Vercel Depencencies"
              run: "npx vercel --prod"
