name: "[CI] Continuous Integration"

# Sempre que tiver um commit ou um PR for aberto
# Quando executar, novos commits ou pr abertos
on:
    pull_request:
        types: [opened, synchronize]

# O que será feito:
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            ## [COMMON_CI_Steps]
            - uses: actions/checkout@v3
            ## =================
            - name: "Debug"
              run: "ls -la"
            - name: "Lint"
              run: "npm run lint"
