name: "[CI] Continuous Integration"

# Sempre que tiver um commit ou um PR for aberto
# Quando executar, novos commits ou pr abertos
on:
    pull_request:
        types: [opened, synchronize]

# O que será feito:
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            ## [COMMON_CI_Steps]
            - uses: actions/checkout@v3
            ## =================
            - name: "Debug"
              run: "ls -la"
            ## Poderia ser utilizado o 'npm install' mas 
            ## no caso do processo de CI/CD é mais interessante e performatico
            ## utilizar o comando 'npm ci' que instala apenas o necessário
            ## para executar a pipeline
            - name: "Install Dependencies"
              run: "npm ci"
            - name: "Lint"
              run: "npm run lint"
    test:
        runs-on: ubuntu-latest
        container: cypress/browsers:node18.20.0-chrome107
        steps:
            ## [COMMON_CI_Steps]
            - uses: actions/checkout@v3
            ## =================
            - name: "Install Dependencies"
              run: "npm ci"
            - name: "Test"
              run: "npm run test"
